#!/usr/bin/env python3
"""
Generate correct BigQuery schemas from CSV headers with fixes for known issues.

Based on EPO PATSTAT schema analysis, this ensures fields like appln_nr are STRING not INT64.
"""

import csv
import sys
import glob
from pathlib import Path

# Fields that should be STRING even if they look numeric
# (e.g., appln_nr can have values like "278120D")
FORCE_STRING_FIELDS = {
    'appln_nr', 'appln_nr_epodoc', 'appln_nr_original',
    'publn_nr', 'publn_nr_original',
    'pat_publn_id',  # Can have non-numeric values in some datasets
}

# Fields that should be INT64
FORCE_INT_FIELDS = {
    'appln_id', 'person_id', 'docdb_family_id', 'inpadoc_family_id',
    'earliest_filing_id', 'earliest_pat_publn_id', 'internat_appln_id',
    'cited_pat_publn_id', 'npl_publn_id',
}

# Fields that are dates
DATE_FIELDS = {
    'appln_filing_date', 'earliest_filing_date', 'earliest_publn_date',
    'publn_date', 'event_date',
}

def infer_schema_from_csv(csv_file):
    """Infer BigQuery schema from CSV header with type corrections."""
    with open(csv_file, 'r', encoding='utf-8', errors='replace') as f:
        reader = csv.reader(f)
        headers = next(reader)

        # Sample first 100 rows
        sample_rows = []
        for i, row in enumerate(reader):
            if i >= 100:
                break
            sample_rows.append(row)

    schema_parts = []
    for i, col in enumerate(headers):
        col_name = col.strip().lower()

        # Apply forced types first
        if col_name in FORCE_STRING_FIELDS:
            col_type = 'STRING'
        elif col_name in FORCE_INT_FIELDS:
            col_type = 'INT64'
        elif col_name in DATE_FIELDS:
            col_type = 'DATE'
        # Infer from patterns
        elif col_name.endswith('_date'):
            col_type = 'DATE'
        elif col_name.endswith('_year'):
            col_type = 'INT64'
        elif col_name.endswith('_id'):
            col_type = 'INT64'
        elif col_name.endswith('_nr'):
            # Number fields often contain non-numeric data in PATSTAT
            col_type = 'STRING'
        elif col_name in ['granted', 'publn_first_grant', 'publn_claims']:
            col_type = 'STRING'  # Y/N values
        elif col_name.endswith('_size') or col_name.endswith('_count'):
            col_type = 'INT64'
        elif col_name == 'weight':
            col_type = 'FLOAT64'
        else:
            # Check sample values
            col_type = 'STRING'
            if sample_rows:
                values = [row[i] if i < len(row) else '' for row in sample_rows]
                values = [v.strip() for v in values if v.strip()]
                if values:
                    # Check if all numeric
                    try:
                        [int(v) for v in values[:10] if v]
                        col_type = 'INT64'
                    except:
                        try:
                            [float(v) for v in values[:10] if v]
                            col_type = 'FLOAT64'
                        except:
                            col_type = 'STRING'

        schema_parts.append(f"{col_name}:{col_type}")

    return ','.join(schema_parts)

def main():
    if len(sys.argv) < 2:
        print("Usage: generate_schemas.py <csv_folder>")
        sys.exit(1)

    folder = Path(sys.argv[1])

    # Find one CSV per table
    csv_files = {}
    for pattern in ['*.csv', '*.CSV']:
        for f in folder.glob(pattern):
            name = f.stem.lower()

            # Handle multipart files
            if '_part' in name:
                base_name = name.split('_part')[0]
            else:
                base_name = name

            # Only process first file of each table
            if base_name not in csv_files:
                csv_files[base_name] = f

    # Generate schemas
    print('"""')
    print('Auto-generated schemas from CSV files.')
    print('Generated by generate_schemas.py')
    print('"""')
    print()
    print('TABLE_SCHEMAS = {')

    for table_name in sorted(csv_files.keys()):
        csv_file = csv_files[table_name]
        try:
            schema = infer_schema_from_csv(csv_file)
            print(f'    "{table_name}": "{schema}",')
        except Exception as e:
            print(f'    # ERROR generating schema for {table_name}: {e}', file=sys.stderr)

    print('}')

if __name__ == '__main__':
    main()
